import "@fontsource/open-sauce-two/300.css";
import "@fontsource/open-sauce-two/400.css";
import "@fontsource/open-sauce-two/500.css";
import "@fontsource/open-sauce-two/600.css";
import "@fontsource/open-sauce-two/700.css";
import "./globals.css";
import { cnm } from "@/utils/style";

export const metadata = {
  title: "BlockEstate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={cnm("font-open-sauce")}>
        {children}
      </body>
    </html>
  );
}
